### ISSUE TITLE
source method_missing in template block

### ISSUE THREAD

**Issue by michaelbarton** [jnicklas/templater#1]
Using the type of block example in the README

```
template :block do
  source('source.rb')
  destination(some_instance_method)
end
```

I get a method missing for the source method. Here's first few lines of stack trace

Generating with model generator:../bin/gigantron:50:in `__instance_exec_1031040_19598780': undefined method`source' for #GigantronGenerators::ModelGenerator:0x2561b78 (NoMethodError) 
from /usr/local/lib/ruby/gems/1.8/gems/templater-0.5.0/lib/templater/core_ext/kernel.rb:7:in `send'
from /usr/local/lib/ruby/gems/1.8/gems/templater-0.5.0/lib/templater/core_ext/kernel.rb:7:in`instance_exec'
from /usr/local/lib/ruby/gems/1.8/gems/templater-0.5.0/lib/templater/generator.rb:233:in `template'

**Comment by jnicklas** [comment]
The documentation is lagging behind, the syntax of the template method is

```
template :block do |t|
  t.source = "foo,rb"
  t.destination = "bar.erb"
end
```

**Comment by michaelbarton** [comment]
Ok, cheers.
