### ISSUE TITLE
Use of to_a and compatibility with Ruby 1.9

### ISSUE THREAD

**Issue by langles** [jnicklas/templater#2]
I've trying to use a library that depends on the templater 0.5 library.  Apparently, the use of the method to_a in:

templater-0.5.0/lib/templater/core_ext/string.rb:5:in `realign_indentation': undefined method`to_a' for "Test String":String (NoMethodError)

is not compatible with Ruby 1.9.  See these links for how to use to_a different in Ruby 1.9:

http://boga.wordpress.com/2008/04/15/ruby-19-porting-notes/
http://blog.grayproductions.net/articles/getting_code_ready_for_ruby_19

**Comment by jnicklas** [comment]
Try using the edge version, this commit: 0b71ca5061821a6093d158f88ff5cf784fc1d8a5 fixes the problem.
